
import java.awt.Desktop;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Saad_BAD
 */
public class Search_Patient extends javax.swing.JFrame {
  

    /**
     * Creates new form Search_Patient
     */
    public Search_Patient() {
        initComponents();
       // lay.setVisible(false);
      
           
         Date date=new Date();


                            String Username="root";
        String password="root123";
     String url = "jdbc:mysql://localhost:3306/lab";


String dateStr2=new Timestamp(date.getTime()).toString();

t1.setText(dateStr2.substring(0,10));
 t2.setText(dateStr2.substring(0,10));       
       
        try{
              Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn=DriverManager.getConnection(url,Username,password);

     String  q1="select Doctor_Name from doctor   ";
     PreparedStatement pst1=null;
   pst1 =conn.prepareStatement(q1); 
    ResultSet rs1=pst1.executeQuery();
    while(rs1.next())
    {
        cb1.addItem(rs1.getString("Doctor_Name"));
    }}catch(Exception ee )
            {
            
            JOptionPane.showMessageDialog(null, ee);
            }
   
    }  
                                       
    
        
        
        
        
       

    

 


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        cbb = new javax.swing.JComboBox<>();
        te = new javax.swing.JTextField();
        jFrame2 = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vw = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t = new javax.swing.JTable();
        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        nt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        c3 = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame1.setMinimumSize(new java.awt.Dimension(400, 300));
        jFrame1.setResizable(false);

        jButton7.setText("View Report");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Modify Data");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Delete Selected");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        cbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "Patients_Name", "Age", "City", "Gender", "Contact_No", "Refered_By", "Type_of_Test", "Ultrasonography_Test", "RadioGraphy_Test", "Price", "Report" }));

        te.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jButton8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(cbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(te, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton7)
                .addGap(80, 80, 80)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addGap(63, 63, 63)
                .addComponent(jButton8)
                .addGap(29, 29, 29)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(te, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jFrame2.setMinimumSize(new java.awt.Dimension(800, 453));
        jFrame2.setResizable(false);

        jLabel8.setText("List of Patients Report");

        vw.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        vw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vwMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(vw);

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(jLabel8)
                .addContainerGap(451, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search ");
        setBackground(new java.awt.Color(27, 15, 32));
        setPreferredSize(new java.awt.Dimension(1366, 700));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Search Report");

        t.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t.setFocusable(false);
        t.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t);

        t1.setText("yyyy-mm-dd");

        jLabel3.setText("Doctor");

        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        c1.setText("Ultrasonography");
        c1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c1ItemStateChanged(evt);
            }
        });
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        c2.setText("RadioGraphy");
        c2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c2ItemStateChanged(evt);
            }
        });
        c2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                c2StateChanged(evt);
            }
        });

        jButton1.setText("Search by Date");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("From");

        jLabel5.setText("To");

        t2.setText("yyyy-mm-dd");

        jLabel2.setText("Total Amount");

        jButton2.setText("Search By Name");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Enter Name");

        l1.setText("Total");

        jButton3.setText("Search By Date,Ultrasongoraohy and Doctor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Search By Date,RadiGraphy and Doctor");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Count");

        c.setText("No");

        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        c3.setText("USG and RadioGraphy");
        c3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c3ItemStateChanged(evt);
            }
        });
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        jButton6.setText("Search By Date USG,RadioGarphy and Doctor ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(nt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton2)))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(c1)
                        .addGap(18, 18, 18)
                        .addComponent(c2)
                        .addGap(18, 18, 18)
                        .addComponent(c3)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(35, 35, 35)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(2, 2, 2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(359, 359, 359)
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)
                        .addComponent(c)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel2)
                        .addGap(80, 80, 80)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(184, 184, 184))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c1)
                            .addComponent(c2)
                            .addComponent(jButton1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(nt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jButton3)
                            .addComponent(jButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c)
                    .addComponent(jButton5)
                    .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void c1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c1ItemStateChanged

       
    }//GEN-LAST:event_c1ItemStateChanged

    private void c2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_c2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_c2StateChanged

    private void c2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c2ItemStateChanged
          
  
       int rowscount=t.getRowCount();
   c.setText(Integer.toString(rowscount));         
            int sum=0;
                    for(int i=0;i<rowscount;i++)
            {
                sum=sum+Integer.parseInt(t.getValueAt(i,10).toString());
            }
                          
                    l1.setText(Integer.toString(sum));
// TODO add your handling code here:
    }//GEN-LAST:event_c2ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            
               
        
    if(c1.isSelected()&&c2.isSelected()==false&&c3.isSelected()==false)    
    { 
     String q;
        
                  String Username="root";
       String password="root123";
                   q = "Select Date,Patients_Name,Age,City,Gender,Contact_No,Refered_By,Type_of_Test,Ultrasonography_Test,RadioGraphy_Test,Price from patient where Date Between ? and ? and Type_of_Test=?";
       String url = "jdbc:mysql://localhost:3306/lab";
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection(url,Username,password);
        PreparedStatement pst=con.prepareStatement(q);
        String u="Ultrasonography";
       pst.setString(1,t1.getText());
       pst.setString(2, t2.getText());
        pst.setString(3,u);
       ResultSet rs= pst.executeQuery();
       t.setModel(DbUtils.resultSetToTableModel(rs));
    
       
          }catch(   ClassNotFoundException | SQLException e){
          
          System.out.println(e);

                int rowscount=t.getRowCount();
   c.setText(Integer.toString(rowscount));         
            int sum=0;
                    for(int i=0;i<rowscount;i++)
            {
                sum=sum+Integer.parseInt(t.getValueAt(i,10).toString());
            }
                          
                    l1.setText(Integer.toString(sum));

          
               }
    }
    else if(c1.isSelected()==false&&c2.isSelected()==true&&c3.isSelected()==false)
    {
             String q;
        
                    String Username="root";
        String password="root123";
                   q = "Select Date,Patients_Name,Age,City,Gender,Contact_No,Refered_By,Type_of_Test,Ultrasonography_Test,RadioGraphy_Test,Price from patient where Date Between ? and ? and Type_of_Test=?";
       String url = "jdbc:mysql://localhost:3306/lab";
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection(url,Username,password);
        PreparedStatement pst=con.prepareStatement(q);
        String u="RadioGraphy";
       pst.setString(1,t1.getText());
       pst.setString(2,t2.getText());
        pst.setString(3,u);
       ResultSet rs= pst.executeQuery();
       t.setModel(DbUtils.resultSetToTableModel(rs));
    
       
          }catch(   ClassNotFoundException | SQLException e){
          
          System.out.println(e);

                int rowscount=t.getRowCount();
   c.setText(Integer.toString(rowscount));         
            int sum=0;
                    for(int i=0;i<rowscount;i++)
            {
                sum=sum+Integer.parseInt(t.getValueAt(i,10).toString());
            }
                          
                    l1.setText(Integer.toString(sum));

          
          
          
          
          
          
               }

    }
    else if(c1.isSelected()==false&&c2.isSelected()==false&&c3.isSelected()==true)
    {
          String q;
        
                    String Username="root";
       String password="root123";

                 //   String Username="root";
       // String password="root123";
        q = "Select Date,Patients_Name,Age,City,Gender,Contact_No,Refered_By,Type_of_Test,Ultrasonography_Test,RadioGraphy_Test,Price from patient where Date Between ? and ? and Type_of_Test=?";
       String url = "jdbc:mysql://localhost:3306/lab";
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection(url,Username,password);
        PreparedStatement pst=con.prepareStatement(q);
        String u="Ultrasonography and RadioGraphy";
       pst.setString(1,t1.getText());
       pst.setString(2,t2.getText());
        pst.setString(3,u);
       ResultSet rs= pst.executeQuery();
       t.setModel(DbUtils.resultSetToTableModel(rs));
    
       
          }catch(   ClassNotFoundException | SQLException e){
          
          System.out.println(e);

          
          
                int rowscount=t.getRowCount();
   c.setText(Integer.toString(rowscount));         
            int sum=0;
                    for(int i=0;i<rowscount;i++)
            {
                sum=sum+Integer.parseInt(t.getValueAt(i,10).toString());
            }
                          
                    l1.setText(Integer.toString(sum));

          
          
          
               }
        
        
    }
    else if(c1.isSelected()&&c2.isSelected()&&c3.isSelected()==false)
    {
     String q;
        
                    String Username="root";
       String password="root123";

                 //   String Username="root";
       // String password="root123";
        q = "Select Date,Patients_Name,Age,City,Gender,Contact_No,Refered_By,Type_of_Test,Ultrasonography_Test,RadioGraphy_Test,Price from patient where Date Between ? and ? and Type_of_Test in('Ultrasonography','Radiography')";
       String url = "jdbc:mysql://localhost:3306/lab";
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection(url,Username,password);
        PreparedStatement pst=con.prepareStatement(q);
       // String u="Ultrasonography and RadioGraphy";
       pst.setString(1,t1.getText());
       pst.setString(2,t2.getText());
       // pst.//setString(3,u);
       ResultSet rs= pst.executeQuery();
       t.setModel(DbUtils.resultSetToTableModel(rs));
    
       
          }catch(   ClassNotFoundException | SQLException e){
          
          System.out.println(e);

          
          
                int rowscount=t.getRowCount();
   c.setText(Integer.toString(rowscount));         
            int sum=0;
                    for(int i=0;i<rowscount;i++)
            {
                sum=sum+Integer.parseInt(t.getValueAt(i,10).toString());
            }
                          
                    l1.setText(Integer.toString(sum));

          } 
          
         
    }
    
    else if(c1.isSelected()&&c2.isSelected()==false&&c3.isSelected())
    {
      
     String q;
        
                    String Username="root";
       String password="root123";

                 //   String Username="root";
       // String password="root123";
        q = "Select Date,Patients_Name,Age,City,Gender,Contact_No,Refered_By,Type_of_Test,Ultrasonography_Test,RadioGraphy_Test,Price from patient where Date Between ? and ? and Type_of_Test in('Ultrasonography','Ultrasonography and RadioGraphy')";
       String url = "jdbc:mysql://localhost:3306/lab";
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection(url,Username,password);
        PreparedStatement pst=con.prepareStatement(q);
       // String u="Ultrasonography and RadioGraphy";
       pst.setString(1,t1.getText());
       pst.setString(2,t2.getText());
       // pst.//setString(3,u);
       ResultSet rs= pst.executeQuery();
       t.setModel(DbUtils.resultSetToTableModel(rs));
    
       
          }catch(   ClassNotFoundException | SQLException e){
          
          System.out.println(e);

          
          
                int rowscount=t.getRowCount();
   c.setText(Integer.toString(rowscount));         
            int sum=0;
                    for(int i=0;i<rowscount;i++)
            {
                sum=sum+Integer.parseInt(t.getValueAt(i,10).toString());
            }
                          
                    l1.setText(Integer.toString(sum));

          } 
        
    } 
    
    else if(c1.isSelected()==false&&c2.isSelected()&&c3.isSelected())
    {
      
     String q;
        
                    String Username="root";
       String password="root123";

                 //   String Username="root";
       // String password="root123";
        q = "Select Date,Patients_Name,Age,City,Gender,Contact_No,Refered_By,Type_of_Test,Ultrasonography_Test,RadioGraphy_Test,Price from patient where Date Between ? and ? and Type_of_Test in('Radiography','Ultrasonography and RadioGraphy')";
       String url = "jdbc:mysql://localhost:3306/lab";
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection(url,Username,password);
        PreparedStatement pst=con.prepareStatement(q);
       // String u="Ultrasonography and RadioGraphy";
       pst.setString(1,t1.getText());
       pst.setString(2,t2.getText());
       // pst.//setString(3,u);
       ResultSet rs= pst.executeQuery();
       t.setModel(DbUtils.resultSetToTableModel(rs));
    
       
          }catch(   ClassNotFoundException | SQLException e){
          
          System.out.println(e);

          
          
                int rowscount=t.getRowCount();
   c.setText(Integer.toString(rowscount));         
            int sum=0;
                    for(int i=0;i<rowscount;i++)
            {
                sum=sum+Integer.parseInt(t.getValueAt(i,10).toString());
            }
                          
                    l1.setText(Integer.toString(sum));

          } 
          
    }
    else if(c1.isSelected()&&c2.isSelected()&&c3.isSelected())
    {
        
     String q;
        
                    String Username="root";
       String password="root123";

                 //   String Username="root";
       // String password="root123";
        q = "Select Date,Patients_Name,Age,City,Gender,Contact_No,Refered_By,Type_of_Test,Ultrasonography_Test,RadioGraphy_Test,Price from patient where Date Between ? and ? and Type_of_Test in('Ultrasonography','Radiography','Ultrasonography and RadioGraphy')";
       String url = "jdbc:mysql://localhost:3306/lab";
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection(url,Username,password);
        PreparedStatement pst=con.prepareStatement(q);
       // String u="Ultrasonography and RadioGraphy";
       pst.setString(1,t1.getText());
       pst.setString(2,t2.getText());
       // pst.//setString(3,u);
       ResultSet rs= pst.executeQuery();
       t.setModel(DbUtils.resultSetToTableModel(rs));
    
       
          }catch(   ClassNotFoundException | SQLException e){
          
          System.out.println(e);

          
          
                int rowscount=t.getRowCount();
   c.setText(Integer.toString(rowscount));         
            int sum=0;
                    for(int i=0;i<rowscount;i++)
            {
                sum=sum+Integer.parseInt(t.getValueAt(i,10).toString());
            }
                          
                    l1.setText(Integer.toString(sum));

          } 
        
    }
    else
        
    {
        
        
        String q;
        
                    String Username="root";
        String password="root123";
                   q = "Select Date,Patients_Name,Age,City,Gender,Contact_No,Refered_By,Type_of_Test,Ultrasonography_Test,RadioGraphy_Test,Price from patient where Date Between ? and ? ";
       String url = "jdbc:mysql://localhost:3306/lab";
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection(url,Username,password);
        PreparedStatement pst=con.prepareStatement(q);
        
        pst.setString(1,t1.getText());
       pst.setString(2,t2.getText());
       ResultSet rs= pst.executeQuery();
       t.setModel(DbUtils.resultSetToTableModel(rs));
       
          }catch(   ClassNotFoundException | SQLException e){
          
          System.out.println(e);

               }        // TODO add your handling code here:

    }
          
          
          
          
          
            
       int rowscount=t.getRowCount();
        
       c.setText(Integer.toString(rowscount));
            int sum=0;
                    for(int i=0;i<rowscount;i++)
            {
                sum=sum+Integer.parseInt(t.getValueAt(i,10).toString());
            }
                          
                    l1.setText(Integer.toString(sum));
          
          
          
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
 String q;
        
                    String Username="root";
        String password="root123";
                   q = "Select Date,Patients_Name,Age,City,Gender,Contact_No,Refered_By,Type_of_Test,Ultrasonography_Test,RadioGraphy_Test,Price from patient where Refered_By=?";
       String url = "jdbc:mysql://localhost:3306/lab";
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection(url,Username,password);
        PreparedStatement pst=con.prepareStatement(q);
        
        pst.setString(1,cb1.getSelectedItem().toString());
             ResultSet rs= pst.executeQuery();
       t.setModel(DbUtils.resultSetToTableModel(rs));
       
          }catch(   ClassNotFoundException | SQLException e){
          
          System.out.println(e);

               }        // TODO add your handling code here:
   
          
  
       int rowscount=t.getRowCount();
   c.setText(Integer.toString(rowscount));         
            int sum=0;
                    for(int i=0;i<rowscount;i++)
            {
                sum=sum+Integer.parseInt(t.getValueAt(i,10).toString());
            }
                          
                    l1.setText(Integer.toString(sum));
// TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   
        String q;
        String   n=nt.getText().toUpperCase();
        
                    String Username="root";
        String password="root123";
                   q = "Select Date,Patients_Name,Age,City,Gender,Contact_No,Refered_By,Type_of_Test,Ultrasonography_Test,RadioGraphy_Test,Price from patient where Patients_Name Like '%"+n+"%'" ;
       String url = "jdbc:mysql://localhost:3306/lab";
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection(url,Username,password);
        PreparedStatement pst=con.prepareStatement(q);
       
       // pst.setString(1,n);
        ResultSet rs= pst.executeQuery();
       t.setModel(DbUtils.resultSetToTableModel(rs));
       
          }catch(   ClassNotFoundException | SQLException e){
          
          System.out.println(e);

               }        // TODO add your handling code here:
                 
        
  
       int rowscount=t.getRowCount();
   c.setText(Integer.toString(rowscount));         
            int sum=0;
                    for(int i=0;i<rowscount;i++)
            {
                sum=sum+Integer.parseInt(t.getValueAt(i,10).toString());
            }
                          
                    l1.setText(Integer.toString(sum));        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMouseClicked
jFrame1.setVisible(true);
              // TODO add your handling code here:
    }//GEN-LAST:event_tMouseClicked

    private void teActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    
        
/*






        
                    String Username="root";
        String password="root123";
                 //  q = "Select Date,Patients_Name,Age,City,Gender,Contact_No,Refered_By,Type_of_Test,Ultrasonography_Test,RadioGraphy_Test,Price,Report from patient where Date = ?";
     String q1="select Patients_Name,Report,Report1,Report2,Report3,Report4,Report5,Report6,Report7,Report8,Report9,Report10 from patient where Patients_Name='"+n+"'";
                   String url = "jdbc:mysql://localhost:3306/lab";
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection(url,Username,password);
       // PreparedStatement pst=con.prepareStatement(q);
        PreparedStatement st1=con.prepareStatement(q1);
        ResultSet rst=st1.executeQuery();
        vw.setModel(DbUtils.resultSetToTableModel(rst));
        jFrame2.setVisible(true);
          }catch(Exception e)
                {
                JOptionPane.showMessageDialog(null,e);
                }
                 
  
  */
        DefaultTableModel model = (DefaultTableModel)t.getModel();

      
        
// get the selected row index
      
           int selectedRowIndex = t.getSelectedRow();
//   c.setText(Integer.toString(rowscount));       
        // set the selected row data into jtextfields
  String  n=model.getValueAt(selectedRowIndex, 1).toString();

  String n2;
  String n1;
  if(model.getValueAt(selectedRowIndex, 8)==null) {
      n2=model.getValueAt(selectedRowIndex, 9).toString();   
       n1=n+n2;
  }
       else
       {
      n2=model.getValueAt(selectedRowIndex, 8).toString();   
     
 n1=n+n2;  
       }
          
  System.out.println(n1);
   
        File file=new File("D://Reports//"+n1+".docx");
  String a="D://Reports//"+n1+".docx";
        
        
        
        
        if(!Desktop.isDesktopSupported())//check if Desktop is supported by Platform or not
            {
                System.out.println("not supported");
                return;
            }
                  
            Desktop desktop = Desktop.getDesktop();
            if(file.exists())
            {try {
                //checks file exists or not
                desktop.open(file);              //opens the specified file
            } catch (IOException ex) {
                Logger.getLogger(Search_Patient.class.getName()).log(Level.SEVERE, null, ex);
            }
            }






        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

String q;
        
                    String Username="root";
        String password="root123";
        
        DefaultTableModel model = (DefaultTableModel)t.getModel();

        // get the selected row index
      
           int selectedRowIndex = t.getSelectedRow();
       
        // set the selected row data into jtextfields
  
      String a=  model.getValueAt(selectedRowIndex, 1).toString();
       System.out.println(a);              
              q = "delete from patient where Patients_Name='"+a+"'";
       String url = "jdbc:mysql://localhost:3306/lab";
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection(url,Username,password);
        PreparedStatement pst=con.prepareStatement(q);
       boolean b= pst.execute();
                       if(b==false)
                       {
                        JOptionPane.showMessageDialog(null,"Deleted successfully");
                       }
                       else
                       {
                        JOptionPane.showMessageDialog(null,"Operattion Unsuccessfully");
                           
                       }
          }catch(   ClassNotFoundException | SQLException e){
          
          System.out.println(e);

               }    






        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

String q;
        
                    String Username="root";
        String password="root123";
        
        DefaultTableModel model = (DefaultTableModel)t.getModel();

        // get the selected row index
      
           int selectedRowIndex = t.getSelectedRow();
       
        // set the selected row data into jtextfields
  
      String a=  model.getValueAt(selectedRowIndex, 1).toString();
      
      if(cbb.getSelectedIndex()==2 ||cbb.getSelectedIndex()==5||cbb.getSelectedIndex()==10 )
      {
          int b=Integer.parseInt(te.getText());
       q = "Update patient set "+cbb.getSelectedItem().toString()+"="+b+" where Patients_Name='"+a+"'";
      }
      else
      {
          String b=te.getText();
       q = "Update patient set "+cbb.getSelectedItem().toString()+"='"+b+"'where Patients_Name='"+a+"'";
      }
          System.out.println(a);              
             // q = "Update patient set "+cbb.getSelectedItem().toString()+"='"+b+"'";
       String url = "jdbc:mysql://localhost:3306/lab";
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection(url,Username,password);
        PreparedStatement pst=con.prepareStatement(q);
       boolean b= pst.execute();
                       if(b==false)
                       {
                        JOptionPane.showMessageDialog(null,"Modifyed Successfully");
                       }
                       else
                       {
                        JOptionPane.showMessageDialog(null,"Operation Unsuccessfully");
                           
                       }
          }catch(   ClassNotFoundException | SQLException e){
          
          System.out.println(e);

               }    


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String q;
        
                    String Username="root";
        String password="root123";
                   q = "Select Date,Patients_Name,Age,City,Gender,Contact_No,Refered_By,Type_of_Test,Ultrasonography_Test,RadioGraphy_Test,Price from patient where Date Between ? and ? and Type_of_Test= 'Ultrasonography' and Refered_By='"+cb1.getSelectedItem().toString()+"'";
       String url = "jdbc:mysql://localhost:3306/lab";
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection(url,Username,password);
        PreparedStatement pst=con.prepareStatement(q);
        
        pst.setString(1,t1.getText());
       pst.setString(2,t2.getText());
       ResultSet rs= pst.executeQuery();
       t.setModel(DbUtils.resultSetToTableModel(rs));
       
          }catch(   ClassNotFoundException | SQLException e){
          
          System.out.println(e);
    
          
          }
          







       int rowscount=t.getRowCount();
   c.setText(Integer.toString(rowscount));         
            int sum=0;
                    for(int i=0;i<rowscount;i++)
            {
                sum=sum+Integer.parseInt(t.getValueAt(i,10).toString());
            }
                          
                    l1.setText(Integer.toString(sum));



// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 String q;
        
                    String Username="root";
        String password="root123";
                   q = "Select Date,Patients_Name,Age,City,Gender,Contact_No,Refered_By,Type_of_Test,Ultrasonography_Test,RadioGraphy_Test,Price from patient where Date Between ? and ? and Type_of_Test= 'RadioGraphy' and Refered_By='"+cb1.getSelectedItem().toString()+"'";
       String url = "jdbc:mysql://localhost:3306/lab";
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection(url,Username,password);
        PreparedStatement pst=con.prepareStatement(q);
        
        pst.setString(1,t1.getText());
       pst.setString(2,t2.getText());
       ResultSet rs= pst.executeQuery();
       t.setModel(DbUtils.resultSetToTableModel(rs));
       
          }catch(   ClassNotFoundException | SQLException e){
          
          System.out.println(e);
          }  // TODO add your handling code here:
       

       int rowscount=t.getRowCount();
   c.setText(Integer.toString(rowscount));         
            int sum=0;
                    for(int i=0;i<rowscount;i++)
            {
                sum=sum+Integer.parseInt(t.getValueAt(i,10).toString());
            }
                          
                    l1.setText(Integer.toString(sum));          





// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
try{
    t.print(JTable.PrintMode.FIT_WIDTH);
}catch(PrinterException e)
{
JOptionPane.showMessageDialog(null, e);
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void vwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vwMouseClicked

int row=vw.getSelectedRow();
int col=vw.getSelectedColumn();
String file_name=vw.getValueAt(row, col).toString();
File file=new File(file_name);
 Desktop desktop = Desktop.getDesktop();
            if(file.exists())
            {try {
                //checks file exists or not
                desktop.open(file);              //opens the specified file
    } catch (IOException ex) {
        Logger.getLogger(Search_Patient.class.getName()).log(Level.SEVERE, null, ex);
    }
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_vwMouseClicked

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void c3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c3ItemStateChanged
//if(c1.isSelected()==true)
  //a    
        
        
        // TODO if(c3.isSelected()) 
       //dd your handling code here:
    }//GEN-LAST:event_c3ItemStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       
        String q;
        
                    String Username="root";
        String password="root123";
                   q = "Select Date,Patients_Name,Age,City,Gender,Contact_No,Refered_By,Type_of_Test,Ultrasonography_Test,RadioGraphy_Test,Price from patient where Date Between ? and ? and Type_of_Test= 'Ultrasonography and RadioGraphy' and Refered_By='"+cb1.getSelectedItem().toString()+"'";
       String url = "jdbc:mysql://localhost:3306/lab";
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection(url,Username,password);
        PreparedStatement pst=con.prepareStatement(q);
        
        pst.setString(1,t1.getText());
       pst.setString(2,t2.getText());
       ResultSet rs= pst.executeQuery();
       t.setModel(DbUtils.resultSetToTableModel(rs));
       
          }catch(   ClassNotFoundException | SQLException e){
          
          System.out.println(e);
    
          
          } // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cbb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l1;
    private javax.swing.JTextField nt;
    private javax.swing.JTable t;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField te;
    private javax.swing.JTable vw;
    // End of variables declaration//GEN-END:variables
}
